name: Create GitHub Release
run-name: Create GitHub Release for args-to-arr ${{ github.ref_name }}

on:
  push:
    tags:
      - v*.*.*

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout, Setup Node.js v20.x and Install dependencies
        uses: manferlo81/action-checkout-node-install@initial
        with:
          node-version: 20.x

      - name: Build
        run: npm run build

      - name: Create Package Tarball
        run: npm pack

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          generate_release_notes: true
          files: args-to-arr-*.tgz
